### ISSUE TITLE
scube:

### ISSUE THREAD

**Issue by JingGuo1997** [QuKunLab/SPACEL#1]
Hello SPACEL developer:

Great software! However, I encountered some problems while using scube. I have two slides marked in the Z-axis as 0 and 1 in the ad.obsm["spatial"] layer. The ad.obsm["aligned_loc_key"] saves the original 2D coordinates of the slides. When I ran Scube.align(inputs, cluster_key='leiden', n_neighbors=25, knn_exclude_cutoff=25, p=2, n_threads=10, aligned_loc_key='aligned_loc_key', raw_loc_key='spatial'), I received the following error message.
slides:
inputs[0].obsm['spatial']
array([[ 5874, 18172,     0],
       [10174, 16172,     0],
       [12324, 16472,     0],
       ...,
       [ 6424, 16422,     0],
       [ 6374, 19972,     0],
       [ 5924, 14172,     0]])

inputs[1].obsm['spatial']
array([[11147,  5110,     1],
       [13097, 10660,     1],
       [16597, 17810,     1],
       ...,
       [13247, 10310,     1],
       [10547, 11260,     1],
       [10297,  9510,     1]])

ERRRO:
Start alignment...
Alignment slice 1 to 0
/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py:495: UserWarning: differential_evolution: the 'workers' keyword has overridden updating='immediate' to updating='deferred'
  warnings.warn("differential_evolution: the 'workers' keyword has"
-----------------------------------
RemoteTracebackTraceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py", line 1261, in __call__
    return self.f(x, *self.args)
  File "/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py", line 92, in score
    return -neighbor_simi_fast(new_source_loc, target_loc, source_cluster, target_cluster, k, knn_exclude_cutoff,p,a)
  File "/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py", line 47, in neighbor_simi_fast
    simi = (((neighbors_cluster - source_cluster[kept_ind].reshape(-1,1)) == 0).sum(1)/(neighbors_cluster!=-1).sum(1)).mean()
TypeError: unsupported operand type(s) for -: 'int' and 'str'
"""

The above exception was the direct cause of the following exception:

TypeErrorTraceback (most recent call last)
/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/_lib/_util.py in __call__(self, func, iterable)
    413         try:
--> 414             return self._mapfunc(func, iterable)
    415         except TypeError:

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    770         else:
--> 771             raise self._value
    772 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py in worker()
    124         try:
--> 125             result = (True, func(*args, **kwds))
    126         except Exception as e:

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/multiprocessing/pool.py in mapstar()
     47 def mapstar(args):
---> 48     return list(map(*args))
     49 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py in __call__()
   1260     def __call__(self, x):
-> 1261         return self.f(x, *self.args)
   1262 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py in score()
     91     new_source_loc[:,1] += warp_param[2]  #y方向平移
---> 92     return -neighbor_simi_fast(new_source_loc, target_loc, source_cluster, target_cluster, k, knn_exclude_cutoff,p,a)
     93 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py in neighbor_simi_fast()
     46         neighbors_cluster[nearest_neighbors!=-1] = target_cluster[nearest_neighbors[nearest_neighbors!=-1]]
---> 47         simi = (((neighbors_cluster - source_cluster[kept_ind].reshape(-1,1)) == 0).sum(1)/(neighbors_cluster!=-1).sum(1)).mean()
     48     else:

TypeError: unsupported operand type(s) for -: 'int' and 'str'

During handling of the above exception, another exception occurred:

TypeErrorTraceback (most recent call last)
/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py in _calculate_population_energies(self, population)
    872         try:
--> 873             calc_energies = list(self._mapwrapper(self.func,
    874                                                   parameters_pop[0:nfevs]))

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/_lib/_util.py in __call__(self, func, iterable)
    416             # wrong number of arguments
--> 417             raise TypeError("The map-like callable must be of the"
    418                             " form f(func, iterable)")

TypeError: The map-like callable must be of the form f(func, iterable)

During handling of the above exception, another exception occurred:

RuntimeErrorTraceback (most recent call last)
<ipython-input-101-5135e3098bb6> in <module>
----> 1 Scube.align(inputs,cluster_key='leiden',n_neighbors=25,knn_exclude_cutoff=25,p=2,n_threads=10,aligned_loc_key='aligned_loc_key', 
      2             raw_loc_key='spatial')

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py in align(ad_list, cluster_key, output_path, raw_loc_key, aligned_loc_key, n_neighbors, knn_exclude_cutoff, p, a, bound_alpha, write_loc_path, n_threads, seed, subset_prop, *args, **kwargs)
    185         source_cluster = np.asarray(ad_list[source_ind].obs[cluster_key])
    186         param = [i, target_xy, source_xy, target_cluster, source_cluster]
--> 187         r = align_pairwise(param, n_neighbors=n_neighbors, knn_exclude_cutoff=knn_exclude_cutoff,p=p,a=a,bound_alpha=bound_alpha, n_threads=n_threads,seed=seed)
    188         res.append(r)
    189 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py in align_pairwise(param, n_neighbors, knn_exclude_cutoff, p, a, bound_alpha, n_threads, *args, **kwargs)
    115 def align_pairwise(param, n_neighbors, knn_exclude_cutoff,p,a,bound_alpha,n_threads,*args,**kwargs):
    116     i, target_loc,source_loc,target_cluster,source_cluster = param
--> 117     flip, result, score, alter_flip, alter_result,alter_score  = optimize(target_loc, source_loc, target_cluster, source_cluster, n_neighbors, knn_exclude_cutoff, p,a,bound_alpha,n_threads,*args,**kwargs)
    118     return [i,flip,result[0],result[1],result[2],score,alter_flip,alter_result[0],alter_result[1],alter_result[2],alter_score]
    119 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/SPACEL-1.0a0-py3.8.egg/SPACEL/Scube/alignment.py in optimize(target_loc, source_loc, target_cluster, source_cluster, n_neighbors, knn_exclude_cutoff, p, a, bound_alpha, n_threads, *args, **kwargs)
     97     source_loc_flip[:,0] = -source_loc_flip[:,0]
     98     func1 = partial(score, target_loc=target_loc, source_loc=source_loc, target_cluster=target_cluster, source_cluster=source_cluster,k=n_neighbors,knn_exclude_cutoff=knn_exclude_cutoff,p=p,a=a)
---> 99     opm1 = differential_evolution(func1, bounds=((0, 360), (target_loc.min(0)[0]*bound_alpha, target_loc.max(0)[0]*bound_alpha), (target_loc.min(0)[1]*bound_alpha, target_loc.max(0)[1]*bound_alpha)),workers=n_threads,*args,**kwargs)
    100     score1 = -opm1.fun
    101     result1 = opm1.x

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py in differential_evolution(func, bounds, args, strategy, maxiter, popsize, tol, mutation, recombination, seed, callback, disp, polish, init, atol, updating, workers, constraints)
    306                                      workers=workers,
    307                                      constraints=constraints) as solver:
--> 308         ret = solver.solve()
    309 
    310     return ret

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py in solve(self)
    748             # only work out population energies for feasible solutions
    749             self.population_energies[self.feasible] = (
--> 750                 self._calculate_population_energies(
    751                     self.population[self.feasible]))
    752 

/home/program/conda/anaconda3/envs/SPACEL/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py in _calculate_population_energies(self, population)
    877             # wrong number of arguments for _mapwrapper
    878             # or wrong length returned from the mapper
--> 879             raise RuntimeError("The map-like callable must be of the"
    880                                " form f(func, iterable), returning a sequence"
    881                                " of numbers the same length as 'iterable'")

RuntimeError: The map-like callable must be of the form f(func, iterable), returning a sequence of numbers the same length as 'iterable'

**Comment by Bink98** [comment]
Hi JingGuo1997, it seems to be a problem with your ```adata.obs['leiden']``` data type, because you are not using the spatial domain identified by Splane as input. In previous versions, it only accepted ```int``` data type but not ```str```, and we have updated the package to support more data type as input than Splane. Please use the latest version to fix this error.

**Comment by JingGuo1997** [comment]
> Hi JingGuo1997, it seems to be a problem with your `adata.obs['leiden']` data type, because you are not using the spatial domain identified by Splane as input. In previous versions, it only accepted `int` data type but not `str`, and we have updated the package to support more data type as input than Splane. Please use the latest version to fix this error.
Okay, I will try. Thank you.

**Comment by JingGuo1997** [comment]
> Hi JingGuo1997, it seems to be a problem with your `adata.obs['leiden']` data type, because you are not using the spatial domain identified by Splane as input. In previous versions, it only accepted `int` data type but not `str`, and we have updated the package to support more data type as input than Splane. Please use the latest version to fix this error.

Okay, I will try. Thank you.

**Comment by JingGuo1997** [comment]
Hi developer, I have downloaded the scube test data and obtained aligned spatial coordinates according to the tutorial:[Scube tutorial: Alignment of multiple spatial transcriptomic slices](https://github.com/QuKunLab/SPACEL/blob/d14f9d28e01c9a18bfff2e48a14f2808b6ad405e/docs/tutorials/alignment_of_multiple_slices.ipynb). However, how can I obtain results similar to Fig. 5 a and e?

**Comment by Bink98** [comment]
You can get a result similar to Figure.5a in the manuscript by setting ```elev=None``` and ```azim=None``` on STARmap dataset, like this:
```
Scube.plot_3d(coo.values[:,:3],val=None,color=coo['celltype_colors'],show=True,elev=None, azim=None, s=1)
```
The ```elev``` and ```azim``` parameters control the view angle, you can get more information [here](https://matplotlib.org/stable/api/toolkits/mplot3d/view_angles.html)

**Comment by JingGuo1997** [comment]
> You can get a result similar to Figure.5a in the manuscript by setting `elev=None` and `azim=None` on STARmap dataset, like this:
> 
> ```
> Scube.plot_3d(coo.values[:,:3],val=None,color=coo['celltype_colors'],show=True,elev=None, azim=None, s=1)
> ```
> 
> The `elev` and `azim` parameters control the view angle, you can get more information [here](https://matplotlib.org/stable/api/toolkits/mplot3d/view_angles.html)

I got the right result Thank you very much
