### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by MingyuYang-Yale** [QuKunLab/SPACEL#10]
Hi,

I am trying to install SPACEL and run the tutorial, but I've met this error: 

![Screenshot 2024-07-05 at 3 36 54 PM](https://github.com/QuKunLab/SPACEL/assets/50332096/bc70e35d-d769-4224-bad0-44c935fec6fa)

Here are the commands I used for installation:

```
conda create -n SPACEL -c conda-forge -c default cudatoolkit=10.2 python=3.8 rpy2 r-base r-fitdistrplus
conda activate SPACEL
conda install -y -c pytorch -c conda-forge cudatoolkit=10.2 pytorch torchvision torchaudio
pip install SPACEL
```

GPU information:
![Screenshot 2024-07-05 at 3 34 34 PM](https://github.com/QuKunLab/SPACEL/assets/50332096/8a8ad87b-db4a-4682-b9a4-1e4dc9b00bdf)

After installation, I verified that pytorch recognizes the GPU:

![Screenshot 2024-07-05 at 3 30 18 PM](https://github.com/QuKunLab/SPACEL/assets/50332096/184e1c98-7a2c-4db0-a7ce-1cec5622e16d)

Can you please assist in resolving this issue? Any help would be greatly appreciated.

Thank you

Best,
Mingyu

**Comment by Bink98** [comment]
It appears that the issue began after the optax library was updated to version 0.1.8, according to this [GitHub issue](https://github.com/google-deepmind/optax/issues/711). You can manually downgrade optax to version 1.1.7 by running the following command: pip install optax==0.1.7.

**Comment by Bink98** [comment]
In order to fix this problem, I have updated the SPACEL package to version 1.1.8.
