### ISSUE TITLE
Cell type composition

### ISSUE THREAD

**Issue by JLiLab** [QuKunLab/SPACEL#2]
Thank you for developing this interesting method! I wonder if Splane can be applied to single-cell resolved dataset. When there is no inferred cell compositions, will that break the code?

**Comment by Bink98** [comment]
Sorry for the late response. In fact, Splane can be applied to single-cell resolution spatial transcriptomic data. In the newest version of SPACEL, we have provided a function called `add_cell_type_composition` for Splane, which allows adding cell type information as input. This function can receive a list of cell type annotations for each cell in single-cell resolution spatial transcriptomic data. For more information, please refer to the documentation: https://spacel.readthedocs.io/en/latest/generated/SPACEL.Splane.utils.add_cell_type_composition.html.
