### ISSUE TITLE
Where to download test data?

### ISSUE THREAD

**Issue by vagabond12** [QuKunLab/SPACEL#3]
Where to download the data of 33 MERFISH slices of mouse brain and other test data? And we found that the download link that you provide is invalid. Thank you very much.

**Comment by Bink98** [comment]
Thanks, we have updated the download link in the tutorial files. The test data in the tutorials can be found at https://zenodo.org/record/8135478

**Comment by DruncBread** [comment]
Hi,  @Bink98 

Thank you for sharing the data!

I downloaded the h5ad files in your link and I wonder if the `adata.obs['spa_cluster']` is the manual annotation (ground truth label)  of the slices.
