### ISSUE TITLE
Large dataset cannot allocate memory using Splane 

### ISSUE THREAD

**Issue by ChanghaoGong** [QuKunLab/SPACEL#4]
I have a large data set with about 1.6 million bins total and 10 samples. When I use Splane for integration, I encounter a problem: 
'torch.matmul cannot allocate memory' at line 198 :f_adj = torch.matmul(encoded, torch.transpose(encoded,0,1)) in the train_model_g function. 
Which will get a 1.6 million*1.6 million matrix, which is obviously impossible. How should I optimize it?

**Comment by Bink98** [comment]
Thanks for your feedback, we have optimized the time and memory consumption of Splane for analyzing large datasets in the new version v1.1.5. I'd be glad to hear further feedback on the new version, and more information about your device.

**Comment by ChanghaoGong** [comment]
Thanks a lot, your update is very helpful and timely!
