### ISSUE TITLE
Too much time is spent training Spoint model

### ISSUE THREAD

**Issue by tqwang743** [QuKunLab/SPACEL#6]
Hi,

It is a fantastic method for analyzing spatial transcriptomics!

When I see the tutorial you write, I find It takes more than three hours to train the model Spoint as shown in the figure below.
<img width="559" alt="1702284213683" src="https://github.com/QuKunLab/SPACEL/assets/108932740/97ca7c54-f25d-4b8c-a6ca-e4f947e4bbf7">

When I tried to retrain the model Spoint, it also took me a lot of time even though I set the value "use_gpu"  to true. I would appreciate it if you could give me some solutions and suggestions to reduce the training time.

Thank you very much!

best,
tqwang

**Comment by Bink98** [comment]
The training time depends on the performance of the device. Could you please provide details of the device you use and the training time?
 If you want to shorten the training time, you can reduce the number of simulated points by setting the `sm_size` parameter in the `Spoint.init_model` function, or reduce the number of genes used by setting the `n_top_markers` parameter. However, we recommend setting `sm_size` to not less than 500000 and  n_top_markers=200 for balancing deconvolution performance and training time.

**Comment by 1062159169** [comment]
你好，我在尝试复现代码教程：人脑Visium数据集上细胞类型成分的反卷积这个部分的时候，运行到可视化结果发生报错，希望您能给我一些解决办法，谢谢！
![Uploading WechatIMG194.jpg…]()
