### ISSUE TITLE
Incorrect column reference in identify_spatial_domain method

### ISSUE THREAD

**Issue by tobias-zehnder** [QuKunLab/SPACEL#8]
https://github.com/QuKunLab/SPACEL/blob/60cf6c131c7af12fe190ee6f61f853b834bddac1/SPACEL/Splane/base_model.py#L343C120-L343C120

Hi there! I was reviewing the `identify_spatial_domain` method and I noticed a potential issue (reference error):

```
self.expr_ad_list[i].uns[f'{key}_colors'] = [color_map.loc[c,'color'] for c in self.expr_ad_list[i].obs['spatial_domain'].cat.categories]
```

It appears that you're referencing the 'spatial_domain' column in the .obs attribute, but I believe it should be using the specified key variable instead.

I suggest updating the line to:

```
self.expr_ad_list[i].uns[f'{key}_colors'] = [color_map.loc[c,'color'] for c in self.expr_ad_list[i].obs[key].cat.categories]
```

This correction ensures that the method correctly utilizes the user-provided key for accessing the spatial domain information.

Thanks for your great work!

**Comment by Bink98** [comment]
Thanks for your careful review! We have fixed this error in the latest version.
