### ISSUE TITLE
复现教程出现的问题

### ISSUE THREAD

**Issue by 1062159169** [QuKunLab/SPACEL#9]
你好，我在尝试复现代码教程：人脑Visium数据集上细胞类型成分的反卷积这个部分时，运行到可视化结果发生报错，希望您能给我一些解决办法，谢谢！
![Uploading WechatIMG194.jpg…]()

**Comment by Bink98** [comment]
你的图片无法打开，请提供具体的运行代码和报错信息

**Comment by 1062159169** [comment]
<img width="1157" alt="image" src="https://github.com/QuKunLab/SPACEL/assets/163981956/45d6215f-9c35-4505-94ef-1b6503945dd5">

**Comment by Bink98** [comment]
请尝试将st_ad.obsm['spatial']从pd.DataFrame对象转换为np.array
